# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:
  couchdb0.org1.luther.systems:
    container_name: couchdb0.org1.luther.systems
    image: $IMAGE_NS/fabric-couchdb:$BASE_IMAGE_TAG
    volumes:
      - "./couchdb/local.ini:/opt/couchdb/etc/local.d/local.ini"
    networks:
      - byfn

  peer0.org1.luther.systems:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.org1.luther.systems:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=peerpassword
    depends_on:
      - couchdb0.org1.luther.systems
