# Copyright © 2021 Luther Systems, Ltd. All right reserved.

FABRIC_IMAGE_TAG=amd64-2.2.0
FABRIC_CA_IMAGE_TAG=amd64-1.5.0
BASE_IMAGE_TAG=amd64-0.4.20
CC_VERSION=${SUBSTRATE_VERSION}

PROJECT_REL_DIR=..
include ${PROJECT_REL_DIR}/common.fabric.mk
include ${PROJECT_REL_DIR}/fabric/common.fullnetwork.mk