// Copyright © 2024 Luther Systems, Ltd. All rights reserved.
// API Models and Documentation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pb/v1/oracle.proto

package v1

import (
	v1 "buf.build/gen/go/luthersystems/protos/protocolbuffers/go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a nationality using an enum for structured validation.
type Nationality int32

const (
	Nationality_NATIONALITY_UNSPECIFIED Nationality = 0 // Default value (should not be used)
	Nationality_NATIONALITY_GB          Nationality = 1 // United Kingdom
	Nationality_NATIONALITY_US          Nationality = 2 // United States
	Nationality_NATIONALITY_FR          Nationality = 3 // France
	Nationality_NATIONALITY_DE          Nationality = 4 // Germany
)

// Enum value maps for Nationality.
var (
	Nationality_name = map[int32]string{
		0: "NATIONALITY_UNSPECIFIED",
		1: "NATIONALITY_GB",
		2: "NATIONALITY_US",
		3: "NATIONALITY_FR",
		4: "NATIONALITY_DE",
	}
	Nationality_value = map[string]int32{
		"NATIONALITY_UNSPECIFIED": 0,
		"NATIONALITY_GB":          1,
		"NATIONALITY_US":          2,
		"NATIONALITY_FR":          3,
		"NATIONALITY_DE":          4,
	}
)

func (x Nationality) Enum() *Nationality {
	p := new(Nationality)
	*p = x
	return p
}

func (x Nationality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Nationality) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_v1_oracle_proto_enumTypes[0].Descriptor()
}

func (Nationality) Type() protoreflect.EnumType {
	return &file_pb_v1_oracle_proto_enumTypes[0]
}

func (x Nationality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Nationality.Descriptor instead.
func (Nationality) EnumDescriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{0}
}

// Represents the final outcome of a claim.
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0 // Default value (should not be used)
	Status_STATUS_APPROVED    Status = 1 // Claim was approved
	Status_STATUS_DECLINED    Status = 2 // Claim was declined
	Status_STATUS_PAID        Status = 3 // Claim has been paid out
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_APPROVED",
		2: "STATUS_DECLINED",
		3: "STATUS_PAID",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_APPROVED":    1,
		"STATUS_DECLINED":    2,
		"STATUS_PAID":        3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_v1_oracle_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_pb_v1_oracle_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{1}
}

// Represents the processing state of the claim (process progress).
type ClaimState int32

const (
	ClaimState_CLAIM_STATE_UNSPECIFIED                ClaimState = 0 // Default value (should not be used)
	ClaimState_CLAIM_STATE_NEW                        ClaimState = 1 // Claim was created
	ClaimState_CLAIM_STATE_LOECLAIM_DETAILS_COLLECTED ClaimState = 2 // Claimant details submitted
	ClaimState_CLAIM_STATE_LOECLAIM_ID_VERIFIED       ClaimState = 3 // Identity verified
	ClaimState_CLAIM_STATE_OOECLAIM_REVIEWED          ClaimState = 4 // Claim reviewed
	ClaimState_CLAIM_STATE_OOECLAIM_VALIDATED         ClaimState = 5 // Claim validated
	ClaimState_CLAIM_STATE_LOEFIN_INVOICE_ISSUED      ClaimState = 6 // Invoice issued
	ClaimState_CLAIM_STATE_OOEFIN_INVOICE_REVIEWED    ClaimState = 7 // Invoice reviewed
	ClaimState_CLAIM_STATE_OOEFIN_INVOICE_APPROVED    ClaimState = 8 // Invoice approved
	ClaimState_CLAIM_STATE_OOEPAY_PAYMENT_TRIGGERED   ClaimState = 9 // Payment triggered
)

// Enum value maps for ClaimState.
var (
	ClaimState_name = map[int32]string{
		0: "CLAIM_STATE_UNSPECIFIED",
		1: "CLAIM_STATE_NEW",
		2: "CLAIM_STATE_LOECLAIM_DETAILS_COLLECTED",
		3: "CLAIM_STATE_LOECLAIM_ID_VERIFIED",
		4: "CLAIM_STATE_OOECLAIM_REVIEWED",
		5: "CLAIM_STATE_OOECLAIM_VALIDATED",
		6: "CLAIM_STATE_LOEFIN_INVOICE_ISSUED",
		7: "CLAIM_STATE_OOEFIN_INVOICE_REVIEWED",
		8: "CLAIM_STATE_OOEFIN_INVOICE_APPROVED",
		9: "CLAIM_STATE_OOEPAY_PAYMENT_TRIGGERED",
	}
	ClaimState_value = map[string]int32{
		"CLAIM_STATE_UNSPECIFIED":                0,
		"CLAIM_STATE_NEW":                        1,
		"CLAIM_STATE_LOECLAIM_DETAILS_COLLECTED": 2,
		"CLAIM_STATE_LOECLAIM_ID_VERIFIED":       3,
		"CLAIM_STATE_OOECLAIM_REVIEWED":          4,
		"CLAIM_STATE_OOECLAIM_VALIDATED":         5,
		"CLAIM_STATE_LOEFIN_INVOICE_ISSUED":      6,
		"CLAIM_STATE_OOEFIN_INVOICE_REVIEWED":    7,
		"CLAIM_STATE_OOEFIN_INVOICE_APPROVED":    8,
		"CLAIM_STATE_OOEPAY_PAYMENT_TRIGGERED":   9,
	}
)

func (x ClaimState) Enum() *ClaimState {
	p := new(ClaimState)
	*p = x
	return p
}

func (x ClaimState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClaimState) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_v1_oracle_proto_enumTypes[2].Descriptor()
}

func (ClaimState) Type() protoreflect.EnumType {
	return &file_pb_v1_oracle_proto_enumTypes[2]
}

func (x ClaimState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClaimState.Descriptor instead.
func (ClaimState) EnumDescriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{2}
}

// Stores details of the claimant (person making the claim).
type Claimant struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber   string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`          // Bank account number (string to support leading zeros)
	AccountSortCode string                 `protobuf:"bytes,2,opt,name=account_sort_code,json=accountSortCode,proto3" json:"account_sort_code,omitempty"`  // Bank sort code (string to avoid leading-zero loss)
	Dob             string                 `protobuf:"bytes,3,opt,name=dob,proto3" json:"dob,omitempty"`                                                   // Date of birth (YYYY-MM-DD)
	Surname         string                 `protobuf:"bytes,4,opt,name=surname,proto3" json:"surname,omitempty"`                                           // Surname (last name)
	Forename        string                 `protobuf:"bytes,5,opt,name=forename,proto3" json:"forename,omitempty"`                                         // Forename (first name)
	FullAddress     string                 `protobuf:"bytes,6,opt,name=full_address,json=fullAddress,proto3" json:"full_address,omitempty"`                // Full address in a single field
	AddressNumber   string                 `protobuf:"bytes,7,opt,name=address_number,json=addressNumber,proto3" json:"address_number,omitempty"`          // House/building number
	AddressStreet1  string                 `protobuf:"bytes,8,opt,name=address_street1,json=addressStreet1,proto3" json:"address_street1,omitempty"`       // Street address
	AddressPostcode string                 `protobuf:"bytes,9,opt,name=address_postcode,json=addressPostcode,proto3" json:"address_postcode,omitempty"`    // Postal code (ZIP code)
	AddressPostTown string                 `protobuf:"bytes,10,opt,name=address_post_town,json=addressPostTown,proto3" json:"address_post_town,omitempty"` // Post town or city
	Nationality     Nationality            `protobuf:"varint,11,opt,name=nationality,proto3,enum=pb.v1.Nationality" json:"nationality,omitempty"`          // Nationality, stored as an enum
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Claimant) Reset() {
	*x = Claimant{}
	mi := &file_pb_v1_oracle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claimant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claimant) ProtoMessage() {}

func (x *Claimant) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claimant.ProtoReflect.Descriptor instead.
func (*Claimant) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{0}
}

func (x *Claimant) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Claimant) GetAccountSortCode() string {
	if x != nil {
		return x.AccountSortCode
	}
	return ""
}

func (x *Claimant) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *Claimant) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *Claimant) GetForename() string {
	if x != nil {
		return x.Forename
	}
	return ""
}

func (x *Claimant) GetFullAddress() string {
	if x != nil {
		return x.FullAddress
	}
	return ""
}

func (x *Claimant) GetAddressNumber() string {
	if x != nil {
		return x.AddressNumber
	}
	return ""
}

func (x *Claimant) GetAddressStreet1() string {
	if x != nil {
		return x.AddressStreet1
	}
	return ""
}

func (x *Claimant) GetAddressPostcode() string {
	if x != nil {
		return x.AddressPostcode
	}
	return ""
}

func (x *Claimant) GetAddressPostTown() string {
	if x != nil {
		return x.AddressPostTown
	}
	return ""
}

func (x *Claimant) GetNationality() Nationality {
	if x != nil {
		return x.Nationality
	}
	return Nationality_NATIONALITY_UNSPECIFIED
}

// Request to create a claim.
type CreateClaimRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DateOfAccident string                 `protobuf:"bytes,1,opt,name=date_of_accident,json=dateOfAccident,proto3" json:"date_of_accident,omitempty"` // Date when the accident occurred (YYYY-MM-DD)
	DamageAmount   int64                  `protobuf:"varint,2,opt,name=damage_amount,json=damageAmount,proto3" json:"damage_amount,omitempty"`        // Damage amount (stored in cents to avoid floating point issues)
	ClaimReason    string                 `protobuf:"bytes,3,opt,name=claim_reason,json=claimReason,proto3" json:"claim_reason,omitempty"`            // Brief description of the reason for the claim
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateClaimRequest) Reset() {
	*x = CreateClaimRequest{}
	mi := &file_pb_v1_oracle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClaimRequest) ProtoMessage() {}

func (x *CreateClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClaimRequest.ProtoReflect.Descriptor instead.
func (*CreateClaimRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{1}
}

func (x *CreateClaimRequest) GetDateOfAccident() string {
	if x != nil {
		return x.DateOfAccident
	}
	return ""
}

func (x *CreateClaimRequest) GetDamageAmount() int64 {
	if x != nil {
		return x.DamageAmount
	}
	return 0
}

func (x *CreateClaimRequest) GetClaimReason() string {
	if x != nil {
		return x.ClaimReason
	}
	return ""
}

// Represents an insurance claim, storing its lifecycle, status, and related claimant details.
type Claim struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClaimId        string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`                        // Unique ID assigned by the backend (immutable)
	State          ClaimState             `protobuf:"varint,2,opt,name=state,proto3,enum=pb.v1.ClaimState" json:"state,omitempty"`                    // The current internal processing state of the claim
	Claimant       *Claimant              `protobuf:"bytes,3,opt,name=claimant,proto3" json:"claimant,omitempty"`                                     // Claimant details
	DateOfAccident string                 `protobuf:"bytes,4,opt,name=date_of_accident,json=dateOfAccident,proto3" json:"date_of_accident,omitempty"` // Date when the accident occurred (YYYY-MM-DD)
	DamageAmount   int64                  `protobuf:"varint,5,opt,name=damage_amount,json=damageAmount,proto3" json:"damage_amount,omitempty"`        // Damage amount (stored in cents to prevent floating point issues)
	ClaimReason    string                 `protobuf:"bytes,6,opt,name=claim_reason,json=claimReason,proto3" json:"claim_reason,omitempty"`            // Description of why the claim was filed
	Status         Status                 `protobuf:"varint,7,opt,name=status,proto3,enum=pb.v1.Status" json:"status,omitempty"`                      // The final outcome of the claim
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Claim) Reset() {
	*x = Claim{}
	mi := &file_pb_v1_oracle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim) ProtoMessage() {}

func (x *Claim) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim.ProtoReflect.Descriptor instead.
func (*Claim) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{2}
}

func (x *Claim) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *Claim) GetState() ClaimState {
	if x != nil {
		return x.State
	}
	return ClaimState_CLAIM_STATE_UNSPECIFIED
}

func (x *Claim) GetClaimant() *Claimant {
	if x != nil {
		return x.Claimant
	}
	return nil
}

func (x *Claim) GetDateOfAccident() string {
	if x != nil {
		return x.DateOfAccident
	}
	return ""
}

func (x *Claim) GetDamageAmount() int64 {
	if x != nil {
		return x.DamageAmount
	}
	return 0
}

func (x *Claim) GetClaimReason() string {
	if x != nil {
		return x.ClaimReason
	}
	return ""
}

func (x *Claim) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

// Response for creating a claim.
type CreateClaimResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CreateClaimResponse_Exception
	//	*CreateClaimResponse_Claim
	Result        isCreateClaimResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClaimResponse) Reset() {
	*x = CreateClaimResponse{}
	mi := &file_pb_v1_oracle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClaimResponse) ProtoMessage() {}

func (x *CreateClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClaimResponse.ProtoReflect.Descriptor instead.
func (*CreateClaimResponse) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{3}
}

func (x *CreateClaimResponse) GetResult() isCreateClaimResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreateClaimResponse) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Result.(*CreateClaimResponse_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

func (x *CreateClaimResponse) GetClaim() *Claim {
	if x != nil {
		if x, ok := x.Result.(*CreateClaimResponse_Claim); ok {
			return x.Claim
		}
	}
	return nil
}

type isCreateClaimResponse_Result interface {
	isCreateClaimResponse_Result()
}

type CreateClaimResponse_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,1,opt,name=exception,proto3,oneof"` // Exception details if an error occurred
}

type CreateClaimResponse_Claim struct {
	Claim *Claim `protobuf:"bytes,2,opt,name=claim,proto3,oneof"` // The created claim if successful
}

func (*CreateClaimResponse_Exception) isCreateClaimResponse_Result() {}

func (*CreateClaimResponse_Claim) isCreateClaimResponse_Result() {}

// Request to update an existing claim.
type AddClaimantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	Claimant      *Claimant              `protobuf:"bytes,2,opt,name=claimant,proto3" json:"claimant,omitempty"` // The claim details with updates
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddClaimantRequest) Reset() {
	*x = AddClaimantRequest{}
	mi := &file_pb_v1_oracle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClaimantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClaimantRequest) ProtoMessage() {}

func (x *AddClaimantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClaimantRequest.ProtoReflect.Descriptor instead.
func (*AddClaimantRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{4}
}

func (x *AddClaimantRequest) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *AddClaimantRequest) GetClaimant() *Claimant {
	if x != nil {
		return x.Claimant
	}
	return nil
}

// Response for updating a claim.
type AddClaimantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*AddClaimantResponse_Exception
	//	*AddClaimantResponse_Claim
	Result        isAddClaimantResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddClaimantResponse) Reset() {
	*x = AddClaimantResponse{}
	mi := &file_pb_v1_oracle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClaimantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClaimantResponse) ProtoMessage() {}

func (x *AddClaimantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClaimantResponse.ProtoReflect.Descriptor instead.
func (*AddClaimantResponse) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{5}
}

func (x *AddClaimantResponse) GetResult() isAddClaimantResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AddClaimantResponse) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Result.(*AddClaimantResponse_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

func (x *AddClaimantResponse) GetClaim() *Claim {
	if x != nil {
		if x, ok := x.Result.(*AddClaimantResponse_Claim); ok {
			return x.Claim
		}
	}
	return nil
}

type isAddClaimantResponse_Result interface {
	isAddClaimantResponse_Result()
}

type AddClaimantResponse_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,1,opt,name=exception,proto3,oneof"` // Exception details if an error occurred
}

type AddClaimantResponse_Claim struct {
	Claim *Claim `protobuf:"bytes,2,opt,name=claim,proto3,oneof"` // The updated claim if successful
}

func (*AddClaimantResponse_Exception) isAddClaimantResponse_Result() {}

func (*AddClaimantResponse_Claim) isAddClaimantResponse_Result() {}

// Request to retrieve a claim by its unique ID.
type GetClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"` // Unique identifier of the claim to fetch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClaimRequest) Reset() {
	*x = GetClaimRequest{}
	mi := &file_pb_v1_oracle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClaimRequest) ProtoMessage() {}

func (x *GetClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClaimRequest.ProtoReflect.Descriptor instead.
func (*GetClaimRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{6}
}

func (x *GetClaimRequest) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

// Response containing the requested claim.
type GetClaimResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetClaimResponse_Exception
	//	*GetClaimResponse_Claim
	Result        isGetClaimResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClaimResponse) Reset() {
	*x = GetClaimResponse{}
	mi := &file_pb_v1_oracle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClaimResponse) ProtoMessage() {}

func (x *GetClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClaimResponse.ProtoReflect.Descriptor instead.
func (*GetClaimResponse) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{7}
}

func (x *GetClaimResponse) GetResult() isGetClaimResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetClaimResponse) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Result.(*GetClaimResponse_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

func (x *GetClaimResponse) GetClaim() *Claim {
	if x != nil {
		if x, ok := x.Result.(*GetClaimResponse_Claim); ok {
			return x.Claim
		}
	}
	return nil
}

type isGetClaimResponse_Result interface {
	isGetClaimResponse_Result()
}

type GetClaimResponse_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,1,opt,name=exception,proto3,oneof"` // Exception details if an error occurred
}

type GetClaimResponse_Claim struct {
	Claim *Claim `protobuf:"bytes,2,opt,name=claim,proto3,oneof"` // The retrieved claim if successful
}

func (*GetClaimResponse_Exception) isGetClaimResponse_Result() {}

func (*GetClaimResponse_Claim) isGetClaimResponse_Result() {}

var File_pb_v1_oracle_proto protoreflect.FileDescriptor

const file_pb_v1_oracle_proto_rawDesc = "" +
	"\n" +
	"\x12pb/v1/oracle.proto\x12\x05pb.v1\x1a\x19common/v1/exception.proto\"\xa5\x03\n" +
	"\bClaimant\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12*\n" +
	"\x11account_sort_code\x18\x02 \x01(\tR\x0faccountSortCode\x12\x10\n" +
	"\x03dob\x18\x03 \x01(\tR\x03dob\x12\x18\n" +
	"\asurname\x18\x04 \x01(\tR\asurname\x12\x1a\n" +
	"\bforename\x18\x05 \x01(\tR\bforename\x12!\n" +
	"\ffull_address\x18\x06 \x01(\tR\vfullAddress\x12%\n" +
	"\x0eaddress_number\x18\a \x01(\tR\raddressNumber\x12'\n" +
	"\x0faddress_street1\x18\b \x01(\tR\x0eaddressStreet1\x12)\n" +
	"\x10address_postcode\x18\t \x01(\tR\x0faddressPostcode\x12*\n" +
	"\x11address_post_town\x18\n" +
	" \x01(\tR\x0faddressPostTown\x124\n" +
	"\vnationality\x18\v \x01(\x0e2\x12.pb.v1.NationalityR\vnationality\"\x86\x01\n" +
	"\x12CreateClaimRequest\x12(\n" +
	"\x10date_of_accident\x18\x01 \x01(\tR\x0edateOfAccident\x12#\n" +
	"\rdamage_amount\x18\x02 \x01(\x03R\fdamageAmount\x12!\n" +
	"\fclaim_reason\x18\x03 \x01(\tR\vclaimReason\"\x91\x02\n" +
	"\x05Claim\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12'\n" +
	"\x05state\x18\x02 \x01(\x0e2\x11.pb.v1.ClaimStateR\x05state\x12+\n" +
	"\bclaimant\x18\x03 \x01(\v2\x0f.pb.v1.ClaimantR\bclaimant\x12(\n" +
	"\x10date_of_accident\x18\x04 \x01(\tR\x0edateOfAccident\x12#\n" +
	"\rdamage_amount\x18\x05 \x01(\x03R\fdamageAmount\x12!\n" +
	"\fclaim_reason\x18\x06 \x01(\tR\vclaimReason\x12%\n" +
	"\x06status\x18\a \x01(\x0e2\r.pb.v1.StatusR\x06status\"{\n" +
	"\x13CreateClaimResponse\x124\n" +
	"\texception\x18\x01 \x01(\v2\x14.common.v1.ExceptionH\x00R\texception\x12$\n" +
	"\x05claim\x18\x02 \x01(\v2\f.pb.v1.ClaimH\x00R\x05claimB\b\n" +
	"\x06result\"\\\n" +
	"\x12AddClaimantRequest\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12+\n" +
	"\bclaimant\x18\x02 \x01(\v2\x0f.pb.v1.ClaimantR\bclaimant\"{\n" +
	"\x13AddClaimantResponse\x124\n" +
	"\texception\x18\x01 \x01(\v2\x14.common.v1.ExceptionH\x00R\texception\x12$\n" +
	"\x05claim\x18\x02 \x01(\v2\f.pb.v1.ClaimH\x00R\x05claimB\b\n" +
	"\x06result\",\n" +
	"\x0fGetClaimRequest\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\"x\n" +
	"\x10GetClaimResponse\x124\n" +
	"\texception\x18\x01 \x01(\v2\x14.common.v1.ExceptionH\x00R\texception\x12$\n" +
	"\x05claim\x18\x02 \x01(\v2\f.pb.v1.ClaimH\x00R\x05claimB\b\n" +
	"\x06result*z\n" +
	"\vNationality\x12\x1b\n" +
	"\x17NATIONALITY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eNATIONALITY_GB\x10\x01\x12\x12\n" +
	"\x0eNATIONALITY_US\x10\x02\x12\x12\n" +
	"\x0eNATIONALITY_FR\x10\x03\x12\x12\n" +
	"\x0eNATIONALITY_DE\x10\x04*[\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTATUS_APPROVED\x10\x01\x12\x13\n" +
	"\x0fSTATUS_DECLINED\x10\x02\x12\x0f\n" +
	"\vSTATUS_PAID\x10\x03*\xfa\x02\n" +
	"\n" +
	"ClaimState\x12\x1b\n" +
	"\x17CLAIM_STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCLAIM_STATE_NEW\x10\x01\x12*\n" +
	"&CLAIM_STATE_LOECLAIM_DETAILS_COLLECTED\x10\x02\x12$\n" +
	" CLAIM_STATE_LOECLAIM_ID_VERIFIED\x10\x03\x12!\n" +
	"\x1dCLAIM_STATE_OOECLAIM_REVIEWED\x10\x04\x12\"\n" +
	"\x1eCLAIM_STATE_OOECLAIM_VALIDATED\x10\x05\x12%\n" +
	"!CLAIM_STATE_LOEFIN_INVOICE_ISSUED\x10\x06\x12'\n" +
	"#CLAIM_STATE_OOEFIN_INVOICE_REVIEWED\x10\a\x12'\n" +
	"#CLAIM_STATE_OOEFIN_INVOICE_APPROVED\x10\b\x12(\n" +
	"$CLAIM_STATE_OOEPAY_PAYMENT_TRIGGERED\x10\tBy\n" +
	"\tcom.pb.v1B\vOracleProtoP\x01Z*github.com/luthersystems/sandbox/api/pb/v1\xa2\x02\x03PXX\xaa\x02\x05Pb.V1\xca\x02\x05Pb\\V1\xe2\x02\x11Pb\\V1\\GPBMetadata\xea\x02\x06Pb::V1b\x06proto3"

var (
	file_pb_v1_oracle_proto_rawDescOnce sync.Once
	file_pb_v1_oracle_proto_rawDescData []byte
)

func file_pb_v1_oracle_proto_rawDescGZIP() []byte {
	file_pb_v1_oracle_proto_rawDescOnce.Do(func() {
		file_pb_v1_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_v1_oracle_proto_rawDesc), len(file_pb_v1_oracle_proto_rawDesc)))
	})
	return file_pb_v1_oracle_proto_rawDescData
}

var file_pb_v1_oracle_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pb_v1_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_v1_oracle_proto_goTypes = []any{
	(Nationality)(0),            // 0: pb.v1.Nationality
	(Status)(0),                 // 1: pb.v1.Status
	(ClaimState)(0),             // 2: pb.v1.ClaimState
	(*Claimant)(nil),            // 3: pb.v1.Claimant
	(*CreateClaimRequest)(nil),  // 4: pb.v1.CreateClaimRequest
	(*Claim)(nil),               // 5: pb.v1.Claim
	(*CreateClaimResponse)(nil), // 6: pb.v1.CreateClaimResponse
	(*AddClaimantRequest)(nil),  // 7: pb.v1.AddClaimantRequest
	(*AddClaimantResponse)(nil), // 8: pb.v1.AddClaimantResponse
	(*GetClaimRequest)(nil),     // 9: pb.v1.GetClaimRequest
	(*GetClaimResponse)(nil),    // 10: pb.v1.GetClaimResponse
	(*v1.Exception)(nil),        // 11: common.v1.Exception
}
var file_pb_v1_oracle_proto_depIdxs = []int32{
	0,  // 0: pb.v1.Claimant.nationality:type_name -> pb.v1.Nationality
	2,  // 1: pb.v1.Claim.state:type_name -> pb.v1.ClaimState
	3,  // 2: pb.v1.Claim.claimant:type_name -> pb.v1.Claimant
	1,  // 3: pb.v1.Claim.status:type_name -> pb.v1.Status
	11, // 4: pb.v1.CreateClaimResponse.exception:type_name -> common.v1.Exception
	5,  // 5: pb.v1.CreateClaimResponse.claim:type_name -> pb.v1.Claim
	3,  // 6: pb.v1.AddClaimantRequest.claimant:type_name -> pb.v1.Claimant
	11, // 7: pb.v1.AddClaimantResponse.exception:type_name -> common.v1.Exception
	5,  // 8: pb.v1.AddClaimantResponse.claim:type_name -> pb.v1.Claim
	11, // 9: pb.v1.GetClaimResponse.exception:type_name -> common.v1.Exception
	5,  // 10: pb.v1.GetClaimResponse.claim:type_name -> pb.v1.Claim
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pb_v1_oracle_proto_init() }
func file_pb_v1_oracle_proto_init() {
	if File_pb_v1_oracle_proto != nil {
		return
	}
	file_pb_v1_oracle_proto_msgTypes[3].OneofWrappers = []any{
		(*CreateClaimResponse_Exception)(nil),
		(*CreateClaimResponse_Claim)(nil),
	}
	file_pb_v1_oracle_proto_msgTypes[5].OneofWrappers = []any{
		(*AddClaimantResponse_Exception)(nil),
		(*AddClaimantResponse_Claim)(nil),
	}
	file_pb_v1_oracle_proto_msgTypes[7].OneofWrappers = []any{
		(*GetClaimResponse_Exception)(nil),
		(*GetClaimResponse_Claim)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_v1_oracle_proto_rawDesc), len(file_pb_v1_oracle_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_v1_oracle_proto_goTypes,
		DependencyIndexes: file_pb_v1_oracle_proto_depIdxs,
		EnumInfos:         file_pb_v1_oracle_proto_enumTypes,
		MessageInfos:      file_pb_v1_oracle_proto_msgTypes,
	}.Build()
	File_pb_v1_oracle_proto = out.File
	file_pb_v1_oracle_proto_goTypes = nil
	file_pb_v1_oracle_proto_depIdxs = nil
}
