// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/luthersystems/sandbox/api/srvpb/oracle.proto

package srvpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	pb "github.com/luthersystems/sandbox/api/pb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("github.com/luthersystems/sandbox/api/srvpb/oracle.proto", fileDescriptor_fe0fdfd0403c7f9d)
}

var fileDescriptor_fe0fdfd0403c7f9d = []byte{
	// 684 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x5d, 0x4f, 0x13, 0x4b,
	0x18, 0xc7, 0xd3, 0x97, 0x43, 0x61, 0x38, 0xe4, 0x94, 0x09, 0x9c, 0x13, 0x0a, 0xe7, 0x64, 0x0e,
	0x78, 0x61, 0x08, 0xdd, 0x6d, 0x0b, 0xf8, 0x42, 0xd4, 0xa4, 0x20, 0x01, 0x62, 0x88, 0x4d, 0xab,
	0x09, 0x12, 0x13, 0x32, 0x9d, 0x7d, 0xd8, 0x8e, 0x4e, 0x67, 0xd6, 0x99, 0xd9, 0x05, 0x34, 0xde,
	0x78, 0xe1, 0xa5, 0x17, 0x78, 0xe7, 0xa5, 0x97, 0x7e, 0x0d, 0xef, 0x8c, 0x77, 0x7e, 0x05, 0x3f,
	0x88, 0xd9, 0xed, 0x36, 0x4a, 0x0b, 0xa9, 0x37, 0x3b, 0x3b, 0xcf, 0xdb, 0x6f, 0xfe, 0xb3, 0xcf,
	0x3e, 0xe8, 0xa6, 0xcf, 0x6d, 0x27, 0x6c, 0x3b, 0x4c, 0x75, 0x5d, 0x11, 0xda, 0x0e, 0x68, 0x73,
	0x66, 0x2c, 0x74, 0x8d, 0x6b, 0xa8, 0xf4, 0xda, 0xea, 0xd4, 0xa5, 0x01, 0x77, 0x8d, 0x8e, 0x82,
	0xb6, 0xab, 0x34, 0x65, 0x02, 0x9c, 0x40, 0x2b, 0xab, 0x70, 0xce, 0xe8, 0xa8, 0xb4, 0xf6, 0x5b,
	0xd9, 0x03, 0xa9, 0xa5, 0x05, 0x5f, 0x29, 0x5f, 0x40, 0xe2, 0xa3, 0x52, 0x2a, 0x4b, 0x2d, 0x57,
	0xd2, 0xa4, 0xde, 0x95, 0x64, 0x61, 0x65, 0x1f, 0x64, 0xd9, 0x9c, 0x50, 0xdf, 0x07, 0xed, 0xaa,
	0x20, 0x89, 0x18, 0x8e, 0xae, 0x7d, 0xcd, 0xa3, 0x62, 0xab, 0xc7, 0x6a, 0x68, 0xc5, 0xc0, 0x18,
	0xa5, 0xb1, 0x40, 0x93, 0xbb, 0x40, 0x85, 0xed, 0x6c, 0x75, 0x80, 0x3d, 0xc7, 0x25, 0x87, 0x79,
	0x5d, 0x67, 0x07, 0xec, 0x2f, 0xc6, 0x26, 0xbc, 0x08, 0xc1, 0xd8, 0xd2, 0xfc, 0xa5, 0x3e, 0x13,
	0x28, 0x69, 0x60, 0xf1, 0xda, 0x79, 0x7d, 0x02, 0x15, 0x5a, 0xa0, 0x23, 0xce, 0xe0, 0xcd, 0xb7,
	0xef, 0xef, 0xb3, 0x18, 0x17, 0xdd, 0xa8, 0xea, 0x76, 0x92, 0xe0, 0x23, 0x96, 0x94, 0x7f, 0x9b,
	0x41, 0x53, 0x5b, 0x1a, 0xa8, 0x85, 0x3a, 0x63, 0x2a, 0x94, 0x16, 0xcf, 0x25, 0x45, 0x2f, 0xd8,
	0xfa, 0xbc, 0xd2, 0x65, 0xae, 0x14, 0x77, 0x6f, 0x08, 0xb7, 0xb2, 0xf8, 0x7f, 0x8c, 0xa3, 0xbd,
	0x40, 0xe3, 0xbe, 0x4a, 0xdf, 0x9c, 0x74, 0x3d, 0xe2, 0xde, 0xeb, 0x8d, 0x42, 0xba, 0xc1, 0x02,
	0xa1, 0x1d, 0xb0, 0xfd, 0x43, 0xfc, 0xdd, 0x57, 0x36, 0x70, 0x82, 0x7f, 0x86, 0xec, 0x29, 0xbe,
	0x3c, 0x84, 0x9f, 0xc7, 0x73, 0x97, 0xe2, 0x63, 0x2c, 0x7e, 0x8a, 0xc6, 0x1f, 0x69, 0x2a, 0xcd,
	0x31, 0x68, 0x3c, 0x93, 0xd4, 0xec, 0x6f, 0xfb, 0xa4, 0xd9, 0x01, 0x6b, 0xca, 0x59, 0x1a, 0xe2,
	0x4c, 0x2f, 0xfe, 0x19, 0x73, 0x6c, 0x1a, 0xb9, 0x91, 0x59, 0xc6, 0x21, 0x9a, 0xba, 0x0f, 0x02,
	0x06, 0xef, 0xf4, 0x82, 0xed, 0xe2, 0x9d, 0x0e, 0xb8, 0xae, 0x16, 0xb5, 0x7c, 0xb5, 0xa8, 0xcd,
	0xcf, 0xf9, 0xf3, 0xfa, 0xbb, 0x3c, 0xc6, 0x68, 0x32, 0x6d, 0x2a, 0x52, 0x6f, 0xec, 0xd5, 0x72,
	0x55, 0xa7, 0xb2, 0x9c, 0xc9, 0xd6, 0x8a, 0x34, 0x08, 0x04, 0x67, 0x49, 0x03, 0xba, 0xcf, 0x8c,
	0x92, 0x1b, 0x43, 0x96, 0xe6, 0x1d, 0x94, 0x5b, 0xab, 0x54, 0xf1, 0x3a, 0x9a, 0xa9, 0x87, 0xb6,
	0xa3, 0x34, 0x7f, 0x99, 0x38, 0xc9, 0x31, 0xe5, 0x02, 0x3c, 0xfc, 0x2f, 0x9a, 0x2f, 0xcd, 0xc5,
	0xff, 0x4b, 0x57, 0x49, 0x67, 0xfb, 0x94, 0x41, 0xd2, 0xd9, 0xfd, 0xe3, 0x36, 0x1b, 0x71, 0x76,
	0x05, 0xef, 0xa1, 0xeb, 0x9b, 0xd4, 0x23, 0xba, 0x27, 0x90, 0x78, 0x60, 0x41, 0x77, 0xb9, 0x04,
	0x8f, 0xb4, 0xcf, 0x48, 0x3b, 0x34, 0x5c, 0x82, 0x31, 0x44, 0x28, 0x9f, 0xb3, 0x51, 0x15, 0x6f,
	0xc5, 0x15, 0xd7, 0x70, 0x15, 0x15, 0xf7, 0xb9, 0x31, 0x5c, 0xfa, 0x44, 0x83, 0x51, 0xa1, 0x66,
	0x30, 0x2a, 0xf3, 0x76, 0x9c, 0xb9, 0x8a, 0x6b, 0x68, 0xba, 0x11, 0xd3, 0x8d, 0x89, 0x65, 0x78,
	0x20, 0xf9, 0x68, 0x19, 0x4b, 0x71, 0xea, 0x3a, 0x5e, 0x40, 0x78, 0x1f, 0x6c, 0x47, 0x79, 0x44,
	0x2a, 0x4b, 0xa8, 0x10, 0xea, 0x04, 0x3c, 0x3c, 0x86, 0xf2, 0x1f, 0xb2, 0x99, 0x42, 0x73, 0x17,
	0xe5, 0xd6, 0x2b, 0x15, 0x5c, 0x47, 0xe4, 0xb1, 0x84, 0xd3, 0x00, 0x98, 0x05, 0x8f, 0x70, 0x69,
	0x41, 0x4b, 0x2a, 0x88, 0x01, 0x1d, 0x81, 0x26, 0xa0, 0xb5, 0xd2, 0xa3, 0x70, 0x77, 0xe3, 0x4a,
	0xab, 0xf8, 0x06, 0x9a, 0x4d, 0x3f, 0x74, 0x8f, 0x17, 0x51, 0x2e, 0x68, 0x5b, 0x8c, 0x12, 0x7a,
	0xf8, 0x1f, 0x5a, 0x40, 0x13, 0x07, 0xe5, 0x7a, 0x63, 0xaf, 0xfc, 0x60, 0xfb, 0x09, 0xfe, 0x6b,
	0x3c, 0x5b, 0xfa, 0xb9, 0x25, 0x59, 0x54, 0x60, 0xaa, 0xeb, 0x18, 0x1d, 0x6d, 0x4e, 0x3e, 0x4c,
	0xc6, 0x58, 0x23, 0x9e, 0x3c, 0x8d, 0xcc, 0xe1, 0x1f, 0xc9, 0x58, 0xfc, 0x98, 0xcd, 0xb5, 0x0e,
	0x0e, 0x3e, 0x65, 0x73, 0x2d, 0x1d, 0x7d, 0x49, 0x9e, 0xed, 0xb1, 0x64, 0x36, 0xad, 0xfe, 0x08,
	0x00, 0x00, 0xff, 0xff, 0xc2, 0xa9, 0x8a, 0x31, 0x5d, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SandboxProcessorClient is the client API for SandboxProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SandboxProcessorClient interface {
	// Check the health of the scaffold processor. This is used by load balancers to check end-to-end service health.
	HealthCheck(ctx context.Context, in *pb.GetHealthCheckRequest, opts ...grpc.CallOption) (*pb.GetHealthCheckResponse, error)
	CreateAccount(ctx context.Context, in *pb.CreateAccountRequest, opts ...grpc.CallOption) (*pb.CreateAccountResponse, error)
	GetAccount(ctx context.Context, in *pb.GetAccountRequest, opts ...grpc.CallOption) (*pb.GetAccountResponse, error)
	Transfer(ctx context.Context, in *pb.TransferRequest, opts ...grpc.CallOption) (*pb.TransferResponse, error)
	DeleteAccount(ctx context.Context, in *pb.DeleteAccountRequest, opts ...grpc.CallOption) (*pb.DeleteAccountResponse, error)
}

type sandboxProcessorClient struct {
	cc *grpc.ClientConn
}

func NewSandboxProcessorClient(cc *grpc.ClientConn) SandboxProcessorClient {
	return &sandboxProcessorClient{cc}
}

func (c *sandboxProcessorClient) HealthCheck(ctx context.Context, in *pb.GetHealthCheckRequest, opts ...grpc.CallOption) (*pb.GetHealthCheckResponse, error) {
	out := new(pb.GetHealthCheckResponse)
	err := c.cc.Invoke(ctx, "/srv.SandboxProcessor/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxProcessorClient) CreateAccount(ctx context.Context, in *pb.CreateAccountRequest, opts ...grpc.CallOption) (*pb.CreateAccountResponse, error) {
	out := new(pb.CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/srv.SandboxProcessor/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxProcessorClient) GetAccount(ctx context.Context, in *pb.GetAccountRequest, opts ...grpc.CallOption) (*pb.GetAccountResponse, error) {
	out := new(pb.GetAccountResponse)
	err := c.cc.Invoke(ctx, "/srv.SandboxProcessor/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxProcessorClient) Transfer(ctx context.Context, in *pb.TransferRequest, opts ...grpc.CallOption) (*pb.TransferResponse, error) {
	out := new(pb.TransferResponse)
	err := c.cc.Invoke(ctx, "/srv.SandboxProcessor/Transfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxProcessorClient) DeleteAccount(ctx context.Context, in *pb.DeleteAccountRequest, opts ...grpc.CallOption) (*pb.DeleteAccountResponse, error) {
	out := new(pb.DeleteAccountResponse)
	err := c.cc.Invoke(ctx, "/srv.SandboxProcessor/DeleteAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxProcessorServer is the server API for SandboxProcessor service.
type SandboxProcessorServer interface {
	// Check the health of the scaffold processor. This is used by load balancers to check end-to-end service health.
	HealthCheck(context.Context, *pb.GetHealthCheckRequest) (*pb.GetHealthCheckResponse, error)
	CreateAccount(context.Context, *pb.CreateAccountRequest) (*pb.CreateAccountResponse, error)
	GetAccount(context.Context, *pb.GetAccountRequest) (*pb.GetAccountResponse, error)
	Transfer(context.Context, *pb.TransferRequest) (*pb.TransferResponse, error)
	DeleteAccount(context.Context, *pb.DeleteAccountRequest) (*pb.DeleteAccountResponse, error)
}

// UnimplementedSandboxProcessorServer can be embedded to have forward compatible implementations.
type UnimplementedSandboxProcessorServer struct {
}

func (*UnimplementedSandboxProcessorServer) HealthCheck(ctx context.Context, req *pb.GetHealthCheckRequest) (*pb.GetHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (*UnimplementedSandboxProcessorServer) CreateAccount(ctx context.Context, req *pb.CreateAccountRequest) (*pb.CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (*UnimplementedSandboxProcessorServer) GetAccount(ctx context.Context, req *pb.GetAccountRequest) (*pb.GetAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (*UnimplementedSandboxProcessorServer) Transfer(ctx context.Context, req *pb.TransferRequest) (*pb.TransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}
func (*UnimplementedSandboxProcessorServer) DeleteAccount(ctx context.Context, req *pb.DeleteAccountRequest) (*pb.DeleteAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccount not implemented")
}

func RegisterSandboxProcessorServer(s *grpc.Server, srv SandboxProcessorServer) {
	s.RegisterService(&_SandboxProcessor_serviceDesc, srv)
}

func _SandboxProcessor_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.GetHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxProcessorServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srv.SandboxProcessor/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxProcessorServer).HealthCheck(ctx, req.(*pb.GetHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxProcessor_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxProcessorServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srv.SandboxProcessor/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxProcessorServer).CreateAccount(ctx, req.(*pb.CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxProcessor_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxProcessorServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srv.SandboxProcessor/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxProcessorServer).GetAccount(ctx, req.(*pb.GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxProcessor_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxProcessorServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srv.SandboxProcessor/Transfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxProcessorServer).Transfer(ctx, req.(*pb.TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxProcessor_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxProcessorServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srv.SandboxProcessor/DeleteAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxProcessorServer).DeleteAccount(ctx, req.(*pb.DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SandboxProcessor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "srv.SandboxProcessor",
	HandlerType: (*SandboxProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _SandboxProcessor_HealthCheck_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _SandboxProcessor_CreateAccount_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _SandboxProcessor_GetAccount_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _SandboxProcessor_Transfer_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _SandboxProcessor_DeleteAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/luthersystems/sandbox/api/srvpb/oracle.proto",
}
