version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    steps:
      - checkout
      - run: echo $LUTHER_LICENSE | base64 -d > .luther-license.yaml
      - run: make citest
