services:
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    networks:
      - byfn
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "3200:3200" # Tempo query port (used by Grafana)
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml

networks:
  byfn:
    external: true
