// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/luthersystems/sandbox/api/pb/oracle.proto

package cdmpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/luthersystems/protos/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Get health status of services.
type GetHealthCheckRequest struct {
	// Skip the chaincode healthcheck
	OracleOnly           bool     `protobuf:"varint,1,opt,name=oracle_only,json=oracleOnly,proto3" json:"oracle_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHealthCheckRequest) Reset()         { *m = GetHealthCheckRequest{} }
func (m *GetHealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*GetHealthCheckRequest) ProtoMessage()    {}
func (*GetHealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde7691b1ed95d8a, []int{0}
}

func (m *GetHealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthCheckRequest.Unmarshal(m, b)
}
func (m *GetHealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *GetHealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthCheckRequest.Merge(m, src)
}
func (m *GetHealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_GetHealthCheckRequest.Size(m)
}
func (m *GetHealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthCheckRequest proto.InternalMessageInfo

func (m *GetHealthCheckRequest) GetOracleOnly() bool {
	if m != nil {
		return m.OracleOnly
	}
	return false
}

// Health status of services.
type GetHealthCheckResponse struct {
	// The status of the relevant sub services.
	Reports []*HealthCheckReport `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	// An exception if an error occurred during processing request.
	Exception            *common.Exception `protobuf:"bytes,2,opt,name=exception,proto3" json:"exception,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetHealthCheckResponse) Reset()         { *m = GetHealthCheckResponse{} }
func (m *GetHealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*GetHealthCheckResponse) ProtoMessage()    {}
func (*GetHealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde7691b1ed95d8a, []int{1}
}

func (m *GetHealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthCheckResponse.Unmarshal(m, b)
}
func (m *GetHealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *GetHealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthCheckResponse.Merge(m, src)
}
func (m *GetHealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_GetHealthCheckResponse.Size(m)
}
func (m *GetHealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthCheckResponse proto.InternalMessageInfo

func (m *GetHealthCheckResponse) GetReports() []*HealthCheckReport {
	if m != nil {
		return m.Reports
	}
	return nil
}

func (m *GetHealthCheckResponse) GetException() *common.Exception {
	if m != nil {
		return m.Exception
	}
	return nil
}

// Health check status of an individual service.
type HealthCheckReport struct {
	// Timestamp of when the report was generated (RFC3339).
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Status of the service.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Name of the service.
	ServiceName string `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Version of the service.
	ServiceVersion       string   `protobuf:"bytes,4,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckReport) Reset()         { *m = HealthCheckReport{} }
func (m *HealthCheckReport) String() string { return proto.CompactTextString(m) }
func (*HealthCheckReport) ProtoMessage()    {}
func (*HealthCheckReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde7691b1ed95d8a, []int{2}
}

func (m *HealthCheckReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckReport.Unmarshal(m, b)
}
func (m *HealthCheckReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckReport.Marshal(b, m, deterministic)
}
func (m *HealthCheckReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckReport.Merge(m, src)
}
func (m *HealthCheckReport) XXX_Size() int {
	return xxx_messageInfo_HealthCheckReport.Size(m)
}
func (m *HealthCheckReport) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckReport.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckReport proto.InternalMessageInfo

func (m *HealthCheckReport) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *HealthCheckReport) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *HealthCheckReport) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *HealthCheckReport) GetServiceVersion() string {
	if m != nil {
		return m.ServiceVersion
	}
	return ""
}

// Request structure for the create_request endponit
type CreateAccountRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde7691b1ed95d8a, []int{3}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type CreateAccountResponse struct {
	Exception            *common.Exception `protobuf:"bytes,1,opt,name=exception,proto3" json:"exception,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde7691b1ed95d8a, []int{4}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetException() *common.Exception {
	if m != nil {
		return m.Exception
	}
	return nil
}

type GetAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde7691b1ed95d8a, []int{5}
}

func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(m, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type GetAccountResponse struct {
	Exception            *common.Exception `protobuf:"bytes,1,opt,name=exception,proto3" json:"exception,omitempty"`
	Account              *Account          `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde7691b1ed95d8a, []int{6}
}

func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(m, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetException() *common.Exception {
	if m != nil {
		return m.Exception
	}
	return nil
}

func (m *GetAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type TransferRequest struct {
	PayerId              string   `protobuf:"bytes,1,opt,name=payer_id,json=payerId,proto3" json:"payer_id,omitempty"`
	PayeeId              string   `protobuf:"bytes,2,opt,name=payee_id,json=payeeId,proto3" json:"payee_id,omitempty"`
	TransferAmount       int64    `protobuf:"varint,3,opt,name=transfer_amount,json=transferAmount,proto3" json:"transfer_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferRequest) Reset()         { *m = TransferRequest{} }
func (m *TransferRequest) String() string { return proto.CompactTextString(m) }
func (*TransferRequest) ProtoMessage()    {}
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde7691b1ed95d8a, []int{7}
}

func (m *TransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferRequest.Unmarshal(m, b)
}
func (m *TransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferRequest.Marshal(b, m, deterministic)
}
func (m *TransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferRequest.Merge(m, src)
}
func (m *TransferRequest) XXX_Size() int {
	return xxx_messageInfo_TransferRequest.Size(m)
}
func (m *TransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferRequest proto.InternalMessageInfo

func (m *TransferRequest) GetPayerId() string {
	if m != nil {
		return m.PayerId
	}
	return ""
}

func (m *TransferRequest) GetPayeeId() string {
	if m != nil {
		return m.PayeeId
	}
	return ""
}

func (m *TransferRequest) GetTransferAmount() int64 {
	if m != nil {
		return m.TransferAmount
	}
	return 0
}

type TransferResponse struct {
	Exception            *common.Exception `protobuf:"bytes,1,opt,name=exception,proto3" json:"exception,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TransferResponse) Reset()         { *m = TransferResponse{} }
func (m *TransferResponse) String() string { return proto.CompactTextString(m) }
func (*TransferResponse) ProtoMessage()    {}
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde7691b1ed95d8a, []int{8}
}

func (m *TransferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferResponse.Unmarshal(m, b)
}
func (m *TransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferResponse.Marshal(b, m, deterministic)
}
func (m *TransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferResponse.Merge(m, src)
}
func (m *TransferResponse) XXX_Size() int {
	return xxx_messageInfo_TransferResponse.Size(m)
}
func (m *TransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransferResponse proto.InternalMessageInfo

func (m *TransferResponse) GetException() *common.Exception {
	if m != nil {
		return m.Exception
	}
	return nil
}

type Account struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CurrentBalance       int64    `protobuf:"varint,2,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde7691b1ed95d8a, []int{9}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Account) GetCurrentBalance() int64 {
	if m != nil {
		return m.CurrentBalance
	}
	return 0
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde7691b1ed95d8a, []int{10}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type DeleteAccountResponse struct {
	Exception            *common.Exception `protobuf:"bytes,1,opt,name=exception,proto3" json:"exception,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeleteAccountResponse) Reset()         { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()    {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde7691b1ed95d8a, []int{11}
}

func (m *DeleteAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResponse.Unmarshal(m, b)
}
func (m *DeleteAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResponse.Merge(m, src)
}
func (m *DeleteAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResponse.Size(m)
}
func (m *DeleteAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResponse proto.InternalMessageInfo

func (m *DeleteAccountResponse) GetException() *common.Exception {
	if m != nil {
		return m.Exception
	}
	return nil
}

func init() {
	proto.RegisterType((*GetHealthCheckRequest)(nil), "cdm.GetHealthCheckRequest")
	proto.RegisterType((*GetHealthCheckResponse)(nil), "cdm.GetHealthCheckResponse")
	proto.RegisterType((*HealthCheckReport)(nil), "cdm.HealthCheckReport")
	proto.RegisterType((*CreateAccountRequest)(nil), "cdm.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "cdm.CreateAccountResponse")
	proto.RegisterType((*GetAccountRequest)(nil), "cdm.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "cdm.GetAccountResponse")
	proto.RegisterType((*TransferRequest)(nil), "cdm.TransferRequest")
	proto.RegisterType((*TransferResponse)(nil), "cdm.TransferResponse")
	proto.RegisterType((*Account)(nil), "cdm.Account")
	proto.RegisterType((*DeleteAccountRequest)(nil), "cdm.DeleteAccountRequest")
	proto.RegisterType((*DeleteAccountResponse)(nil), "cdm.DeleteAccountResponse")
}

func init() {
	proto.RegisterFile("github.com/luthersystems/sandbox/api/pb/oracle.proto", fileDescriptor_cde7691b1ed95d8a)
}

var fileDescriptor_cde7691b1ed95d8a = []byte{
	// 541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xd1, 0x6e, 0xd3, 0x3c,
	0x14, 0x56, 0x9a, 0xfd, 0xeb, 0x7a, 0x32, 0x6d, 0xff, 0xac, 0xb5, 0x2a, 0x08, 0x44, 0xc9, 0x05,
	0xf4, 0x86, 0x04, 0x0a, 0x48, 0x5c, 0x21, 0xad, 0x05, 0xad, 0xbd, 0x61, 0x53, 0x84, 0xd0, 0xc4,
	0x4d, 0xe5, 0x38, 0x07, 0x1a, 0x11, 0xdb, 0xc1, 0x76, 0xa6, 0x55, 0x3c, 0x07, 0x2f, 0xc0, 0x25,
	0x8f, 0xc2, 0x53, 0xa1, 0x38, 0x09, 0xed, 0x3a, 0x89, 0xa1, 0xde, 0x44, 0xf6, 0x77, 0xbe, 0xe3,
	0xf3, 0x9d, 0xef, 0x38, 0x86, 0x17, 0x9f, 0x53, 0xb3, 0x28, 0xe2, 0x80, 0x49, 0x1e, 0x66, 0x85,
	0x59, 0xa0, 0xd2, 0x4b, 0x6d, 0x90, 0xeb, 0x50, 0x53, 0x91, 0xc4, 0xf2, 0x2a, 0xa4, 0x79, 0x1a,
	0xe6, 0x71, 0x28, 0x15, 0x65, 0x19, 0x06, 0xb9, 0x92, 0x46, 0x12, 0x97, 0x25, 0xfc, 0xae, 0x6f,
	0xd7, 0xfa, 0x09, 0xa7, 0xa9, 0x08, 0x99, 0xe4, 0x5c, 0x8a, 0x10, 0xaf, 0x18, 0xe6, 0x26, 0x95,
	0xa2, 0x22, 0xfa, 0xaf, 0xa0, 0x7b, 0x8a, 0x66, 0x8a, 0x34, 0x33, 0x8b, 0xc9, 0x02, 0xd9, 0x97,
	0x08, 0xbf, 0x16, 0xa8, 0x0d, 0x79, 0x00, 0x5e, 0x75, 0xe2, 0x5c, 0x8a, 0x6c, 0xd9, 0x77, 0x06,
	0xce, 0x70, 0x2f, 0x82, 0x0a, 0x3a, 0x13, 0xd9, 0xd2, 0xff, 0x06, 0xbd, 0xcd, 0x4c, 0x9d, 0x4b,
	0xa1, 0x91, 0x3c, 0x85, 0xb6, 0xc2, 0x5c, 0x2a, 0xa3, 0xfb, 0xce, 0xc0, 0x1d, 0x7a, 0xa3, 0x5e,
	0xc0, 0x12, 0x1e, 0x5c, 0xa3, 0x96, 0xe1, 0xa8, 0xa1, 0x91, 0x10, 0x3a, 0x7f, 0x84, 0xf5, 0x5b,
	0x03, 0x67, 0xe8, 0x8d, 0x8e, 0x82, 0x4a, 0x71, 0xf0, 0xb6, 0x09, 0x44, 0x2b, 0x8e, 0xff, 0xdd,
	0x81, 0xa3, 0x1b, 0xe7, 0x91, 0x7b, 0xd0, 0x31, 0x29, 0x47, 0x6d, 0x28, 0xcf, 0xad, 0xe2, 0x4e,
	0xb4, 0x02, 0x48, 0x0f, 0x76, 0xb5, 0xa1, 0xa6, 0xd0, 0xb6, 0x42, 0x27, 0xaa, 0x77, 0xe4, 0x21,
	0xec, 0x6b, 0x54, 0x97, 0x29, 0xc3, 0xb9, 0xa0, 0x1c, 0xfb, 0xae, 0x8d, 0x7a, 0x35, 0xf6, 0x8e,
	0x72, 0x24, 0x8f, 0xe1, 0xb0, 0xa1, 0x5c, 0xa2, 0xd2, 0xa5, 0xca, 0x1d, 0xcb, 0x3a, 0xa8, 0xe1,
	0x0f, 0x15, 0xea, 0xbf, 0x86, 0xe3, 0x89, 0x42, 0x6a, 0xf0, 0x84, 0x31, 0x59, 0x08, 0xd3, 0xb8,
	0xf9, 0x08, 0xda, 0xb4, 0x42, 0xac, 0x2e, 0x6f, 0xb4, 0x6f, 0x2d, 0x69, 0x58, 0x4d, 0xd0, 0x9f,
	0x42, 0x77, 0x23, 0xbf, 0xf6, 0xf4, 0x9a, 0x43, 0xce, 0x3f, 0x38, 0x34, 0x82, 0xa3, 0x53, 0x34,
	0x1b, 0x32, 0xee, 0x03, 0xd4, 0x95, 0xe6, 0x69, 0xd2, 0x38, 0x54, 0x23, 0xb3, 0xc4, 0xe7, 0x40,
	0xd6, 0x73, 0xb6, 0x2c, 0xbd, 0xde, 0x6c, 0xeb, 0x6f, 0xcd, 0xe6, 0x70, 0xf8, 0x5e, 0x51, 0xa1,
	0x3f, 0xa1, 0x6a, 0x04, 0xde, 0x81, 0xbd, 0x9c, 0x2e, 0x51, 0xad, 0xe4, 0xb5, 0xed, 0x7e, 0x96,
	0x34, 0x21, 0x2c, 0x43, 0xad, 0x55, 0x08, 0x67, 0x49, 0x39, 0x1e, 0x53, 0x1f, 0x34, 0xa7, 0xdc,
	0x16, 0x2e, 0x87, 0xe8, 0x46, 0x07, 0x0d, 0x7c, 0x62, 0x51, 0x7f, 0x02, 0xff, 0xaf, 0x2a, 0x6e,
	0xeb, 0x2c, 0x42, 0xbb, 0x6e, 0xe5, 0x16, 0x3f, 0x4b, 0x5d, 0xac, 0x50, 0x0a, 0x85, 0x99, 0xc7,
	0x34, 0xa3, 0x82, 0xa1, 0x55, 0xee, 0x46, 0x07, 0x35, 0x3c, 0xae, 0x50, 0x42, 0x60, 0x67, 0xed,
	0xea, 0xd9, 0xb5, 0xff, 0x12, 0x8e, 0xdf, 0x60, 0x86, 0x37, 0xae, 0xd2, 0x2d, 0x33, 0x9c, 0x42,
	0x77, 0x23, 0x6d, 0xcb, 0x3e, 0xc7, 0xcf, 0xa0, 0xcd, 0x24, 0x2f, 0x47, 0x37, 0xf6, 0xce, 0xec,
	0x7f, 0x7f, 0x5e, 0x3e, 0x19, 0xe7, 0xce, 0xc7, 0xff, 0x58, 0xc2, 0xf3, 0xf8, 0x47, 0xcb, 0x9d,
	0x5c, 0x5c, 0xfc, 0x6c, 0xb9, 0x93, 0x84, 0xff, 0xb2, 0xdf, 0x78, 0xd7, 0x3e, 0x2a, 0xcf, 0x7f,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xed, 0x79, 0x1a, 0xe5, 0xb5, 0x04, 0x00, 0x00,
}
