// Copyright © 2024 Luther Systems, Ltd. All right reserved.

// API Specification and Documentation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: srvpb/v1/oracle.proto

package srv

import (
	v1 "buf.build/gen/go/luthersystems/protos/protocolbuffers/go/healthcheck/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v11 "github.com/luthersystems/sandbox/api/pb/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_srvpb_v1_oracle_proto protoreflect.FileDescriptor

const file_srvpb_v1_oracle_proto_rawDesc = "" +
	"\n" +
	"\x15srvpb/v1/oracle.proto\x12\bsrvpb.v1\x1a\x1cgoogle/api/annotations.proto\x1a healthcheck/v1/healthcheck.proto\x1a\x12pb/v1/oracle.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\x82\x04\n" +
	"\x0eSandboxService\x12\x8d\x01\n" +
	"\x0eGetHealthCheck\x12%.healthcheck.v1.GetHealthCheckRequest\x1a&.healthcheck.v1.GetHealthCheckResponse\",\x92A\t\n" +
	"\aService\x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/sandbox/health_check\x12l\n" +
	"\vCreateClaim\x12\x19.pb.v1.CreateClaimRequest\x1a\x1a.pb.v1.CreateClaimResponse\"&\x92A\t\n" +
	"\aService\x82\xd3\xe4\x93\x02\x14\"\x12/v1/sandbox/claims\x12\x82\x01\n" +
	"\vAddClaimant\x12\x19.pb.v1.AddClaimantRequest\x1a\x1a.pb.v1.AddClaimantResponse\"<\x92A\t\n" +
	"\aService\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/sandbox/claim/{claim_id}/claimant\x12m\n" +
	"\bGetClaim\x12\x16.pb.v1.GetClaimRequest\x1a\x17.pb.v1.GetClaimResponse\"0\x92A\t\n" +
	"\aService\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/sandbox/claim/{claim_id}B\xaa\x05\x92A\xa0\x04\x12\x12\n" +
	"\vSandbox API2\x031.0*\x01\x022\x10application/json:\x10application/jsonRS\n" +
	"\x03400\x12L\n" +
	"(Bad request determined by business logic\x12 \n" +
	"\x1e\x1a\x1c.common.v1.ExceptionResponseR?\n" +
	"\x03401\x128\n" +
	"\x14Authorization failed\x12 \n" +
	"\x1e\x1a\x1c.common.v1.ExceptionResponseR<\n" +
	"\x03403\x125\n" +
	"\x11Permission denied\x12 \n" +
	"\x1e\x1a\x1c.common.v1.ExceptionResponseR;\n" +
	"\x03404\x124\n" +
	"\x10Missing resource\x12 \n" +
	"\x1e\x1a\x1c.common.v1.ExceptionResponseR#\n" +
	"\x03405\x12\x1c\n" +
	"\x12Method not allowed\x12\x06\n" +
	"\x04\x9a\x02\x01\aRK\n" +
	"\x03500\x12D\n" +
	" Unexpected internal server error\x12 \n" +
	"\x1e\x1a\x1c.common.v1.ExceptionResponseR@\n" +
	"\x03503\x129\n" +
	"\x15Service not available\x12 \n" +
	"\x1e\x1a\x1c.common.v1.ExceptionResponseZ\x1e\n" +
	"\x1c\n" +
	"\tX-API-KEY\x12\x0f\b\x02\x1a\tX-API-KEY \x02\n" +
	"\fcom.srvpb.v1B\vOracleProtoP\x01Z(github.com/luthersystems/sandbox/api/srv\xa2\x02\x03SXX\xaa\x02\bSrvpb.V1\xca\x02\bSrvpb\\V1\xe2\x02\x14Srvpb\\V1\\GPBMetadata\xea\x02\tSrvpb::V1b\x06proto3"

var file_srvpb_v1_oracle_proto_goTypes = []any{
	(*v1.GetHealthCheckRequest)(nil),  // 0: healthcheck.v1.GetHealthCheckRequest
	(*v11.CreateClaimRequest)(nil),    // 1: pb.v1.CreateClaimRequest
	(*v11.AddClaimantRequest)(nil),    // 2: pb.v1.AddClaimantRequest
	(*v11.GetClaimRequest)(nil),       // 3: pb.v1.GetClaimRequest
	(*v1.GetHealthCheckResponse)(nil), // 4: healthcheck.v1.GetHealthCheckResponse
	(*v11.CreateClaimResponse)(nil),   // 5: pb.v1.CreateClaimResponse
	(*v11.AddClaimantResponse)(nil),   // 6: pb.v1.AddClaimantResponse
	(*v11.GetClaimResponse)(nil),      // 7: pb.v1.GetClaimResponse
}
var file_srvpb_v1_oracle_proto_depIdxs = []int32{
	0, // 0: srvpb.v1.SandboxService.GetHealthCheck:input_type -> healthcheck.v1.GetHealthCheckRequest
	1, // 1: srvpb.v1.SandboxService.CreateClaim:input_type -> pb.v1.CreateClaimRequest
	2, // 2: srvpb.v1.SandboxService.AddClaimant:input_type -> pb.v1.AddClaimantRequest
	3, // 3: srvpb.v1.SandboxService.GetClaim:input_type -> pb.v1.GetClaimRequest
	4, // 4: srvpb.v1.SandboxService.GetHealthCheck:output_type -> healthcheck.v1.GetHealthCheckResponse
	5, // 5: srvpb.v1.SandboxService.CreateClaim:output_type -> pb.v1.CreateClaimResponse
	6, // 6: srvpb.v1.SandboxService.AddClaimant:output_type -> pb.v1.AddClaimantResponse
	7, // 7: srvpb.v1.SandboxService.GetClaim:output_type -> pb.v1.GetClaimResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_srvpb_v1_oracle_proto_init() }
func file_srvpb_v1_oracle_proto_init() {
	if File_srvpb_v1_oracle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_srvpb_v1_oracle_proto_rawDesc), len(file_srvpb_v1_oracle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_srvpb_v1_oracle_proto_goTypes,
		DependencyIndexes: file_srvpb_v1_oracle_proto_depIdxs,
	}.Build()
	File_srvpb_v1_oracle_proto = out.File
	file_srvpb_v1_oracle_proto_goTypes = nil
	file_srvpb_v1_oracle_proto_depIdxs = nil
}
